# <center> Python - Sesión Numpy </center>

# Librería Numpy

NumPy es una librería de Python especializada en el cálculo numérico y el análisis de datos, especialmente para un gran volumen de datos.

Incorpora una nueva clase de objetos llamados arrays que permite representar colecciones de datos de un mismo tipo en varias dimensiones, y funciones muy eficientes para su manipulación.

La ventaja de Numpy frente a las listas predefinidas en Python es que el procesamiento de los arrays se realiza mucho más rápido (hasta 50 veces más) que las listas, lo cual la hace ideal para el procesamiento de vectores y matrices de grandes dimensiones.

## La clase de objetos array
Un array es una estructura de datos de un mismo tipo organizada en forma de tabla o cuadrícula de distintas dimensiones.

Las dimensiones de un array también se conocen como ejes.

## Creación de arrays
Para crear un array se utiliza la siguiente función de NumPy (np)

* np.array(lista) : Crea un array a partir de la lista o tupla lista y devuelve una referencia a él. El número de dimensiones del array dependerá de las **listas o tuplas anidadas** en lista:
* Para una lista de valores se crea un array de una dimensión, también conocido como vector.
* Para una lista de listas de valores se crea un array de dos dimensiones, también conocido como matriz.
* Para una lista de listas de listas de valores se crea un array de tres dimensiones, también conocido como cubo.
* Y así sucesivamente. No hay límite en el número de dimensiones del array más allá de la memoria disponible en el sistema.


In [1]:
# Num = Numero , Py = python
# !pip = indica a python buscar en internet y/o sus librerias internas a Numpy, para posterior hacer su instalacion.
# install = instala la libreria

!pip install numpy

In [2]:
# Importar desde python la libreria nupy e asignarle un alias a la libreria
import numpy as np

In [3]:
## Como obtener la version del numpy
np.__version__

'1.26.4'

In [4]:
# numpy = np
np.array((8,10,1992,19,6,1989))

array([   8,   10, 1992,   19,    6, 1989])

In [5]:
# numpy = np
np.array([8,10,1992,19,6,1989])

array([   8,   10, 1992,   19,    6, 1989])

In [6]:
arrDany = np.array((8,10,1992,19,6,1989))

In [7]:
type(arrDany)

numpy.ndarray

In [8]:
#Estamos creando un array con una sola dimension
np.array((89,90,120,45,75))

array([ 89,  90, 120,  45,  75])

In [9]:
# Asignando el valor de un array a una variable

a1 = np.array([1, 2, 3])
type(a1)

numpy.ndarray

In [19]:
#crendo un arreglo con 2 dimensiones
## Matrices

## Orden de lectura
### Fila seguido columna

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print(arr2)
print(arr2.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [13]:
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a3)
print(a3.size)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12


In [21]:
arr2 = np.ones((3,4,3),dtype = int)
arr2

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [16]:
a = np.array([[[1, 2, 3], [4, 5, 6],[7, 8, 9]] , [[10, 11, 12],[13, 14, 15],[16, 17, 18]], [[10, 11, 12],[13, 14, 15],[16, 17, 18]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

## Otras funciones útiles que permiten generar arrays son:

* np.empty(dimensiones) : Crea y devuelve una referencia a un array vacío con las dimensiones especificadas en la tupla dimensiones.
* np.zeros(dimensiones) : Crea y devuelve una referencia a un array con las dimensiones especificadas en la tupla dimensiones cuyos elementos son todos ceros.
* np.ones(dimensiones) : Crea y devuelve una referencia a un array con las dimensiones especificadas en la tupla dimensiones cuyos elementos son todos unos.

* np.linspace(inicio, fin, n) : Crea y devuelve una referencia a un array de una dimensión cuyos elementos son la secuencia de n valores equidistantes desde inicio hasta fin.
* np.random.random(dimensiones) : Crea y devuelve una referencia a un array con las dimensiones especificadas en la tupla dimensiones cuyos elementos son aleatorios.

In [ ]:
#crear una array de 10 datos flotantes, con valores cero "0"
npp= np.zeros(3)

In [22]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
#Creando un array de 2 dimensiones con 8 datos
#Valor a la izquierda (filas), valor a la derecha (columnas)
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
#Creando un array de 2 dimensiones con 18 datos
# valor a la izquierda (filas), valor a la derecha (columnas)
np.zeros((3,6), dtype = int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [26]:
#Crear un array con valores de numero 1, segun la cantidad de datos que yo le indique
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
#Crear un array con valores de numero 1, segun la cantidad de datos que yo le indique
np.ones(10, dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [28]:
# Creando un arreglo de 2 dimensiones con numpy y la funcion ones
# valor a la izquierda (filas), valor a la derecha (columnas)

np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
# Creando un arreglo de 2 dimensiones con numpy y la funcion ones
# valor a la izquierda (filas), valor a la derecha (columnas)

np.ones((4,2), dtype = int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [31]:
# Indicamos el rango de los valores que va a tener este arreglo
# Termina en el numero 9, porque en python el valor que te devuelve es el valor setado - 1
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# indicamos el rango de los datos que devovera
# El ultimo valor indicado, siempre va a tener que descontarle -1
np.arange(4,11)

array([ 4,  5,  6,  7,  8,  9, 10])

In [33]:
#Creando un arreglo, donde le indico el inicio, fin y su salto de valor en valor.
array_rango = np.arange(0,501,10)

In [34]:
array_rango

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250,
       260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380,
       390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500])

In [36]:
# Asignando el valor de un arreglo randon de 30 caracteres a una variable
# Random con numeros flotantes
array = np.random.randn(30) # los numeros random que te entregan, estan cerca al valor de cero.
array

array([-0.00740776,  1.43098585, -2.16863152,  0.71864574,  0.59386466,
       -0.14416893,  0.12206519, -1.30508688,  1.11712853,  1.21969912,
       -0.40428619, -0.09404906,  1.03539675, -0.60965354,  0.04311216,
        1.45021787, -1.8061524 , -2.00043451, -0.65756711,  0.3256531 ,
       -0.7490901 ,  0.70433679,  0.93374102, -0.41124725,  0.99279341,
        0.16093   , -0.51568131,  0.08643636,  2.22761244,  0.58144855])

In [ ]:
# Me va a permitir agregar valores randon, donde incicamos el valor incial, valor final y la cantidad de valores que va a devolver
# Inicias en 0, terminas maximo en 10 y solo devuelves 5 valores.
arr2 = np.random.uniform(-10,10,30)
arr2

array([-0.43611807, -2.17745664, -2.73328374,  2.30189538, -6.94972836,
       -2.83126931,  7.90848184, -8.64448996, -0.67064367, -5.27167018,
        5.82991353,  7.55738465,  9.91674872,  9.76033805,  6.24083691,
       -2.68493486,  6.19069211, -7.4806588 , -0.24168004,  4.04899487,
        1.73203038, -3.64060481,  0.17872195,  3.95259224, -8.17713543,
       -1.40082246, -5.20886506, -0.91959247, -8.24121308, -9.18583452])

In [41]:
# Inicias en 0, terminas maximo en 10 y solo devuelves 10 valores.
arr3 = np.random.randint(-10,10,45)
arr3

array([ -6,   8,   9,   5, -10,   1,   7,   4,   6,   9,   8,  -8,   1,
         1,  -1,  -7,  -8,  -1,   3,  -1,  -9,   7,  -3,  -8,   3,   9,
        -4,   1,  -7,   0,  -4,   8,   1,  -5,  -9,  -4,   0,   0,  -8,
         9,   9,   9,   8,  -4,   0])

In [43]:
### reshape, lo que nos permite es dividir el arreglo indicado por la cantidad requerida
# valor a la izquierda (filas), valor a la derecha (columnas)

arr3.reshape(3,3,5)

array([[[ -6,   8,   9,   5, -10],
        [  1,   7,   4,   6,   9],
        [  8,  -8,   1,   1,  -1]],

       [[ -7,  -8,  -1,   3,  -1],
        [ -9,   7,  -3,  -8,   3],
        [  9,  -4,   1,  -7,   0]],

       [[ -4,   8,   1,  -5,  -9],
        [ -4,   0,   0,  -8,   9],
        [  9,   9,   8,  -4,   0]]])

## Atributos de un array
Existen varios atributos y funciones que describen las características de un array.

* a.ndim : Devuelve el número de dimensiones del array a.
* a.shape : Devuelve una tupla 'entre parentesis' con las dimensiones del array a.
* a.size : Devuelve el número de elementos del array a.
* a.dtype: Devuelve el tipo de datos de los elementos del array a.


In [49]:
#Creamos un arreglo de 3 dimensiones
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a)
print(a.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [45]:
#Creamos un arreglo de 2 dimensiones

a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
# print devuelve el valor del array sin comas
print(a)

[[1 2 3]
 [4 5 6]]


In [52]:
# Nos permite indicar cuantas dimensiones tiene un arreglo
a.ndim

3

In [51]:
# 2 para el eje X,
# 2 para el eje Y,
# 3 para el eje Z

## Cuantas filas tiene y cuantas columnas tiene en ese orden
print(a)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [53]:
#a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(a.ndim)
a.shape

3


(2, 2, 3)

In [ ]:
# Para el calculo de los elementos que tiene un arreglo de 3 dimensiones hacemos el calculo de su lados.
a.size

6

In [55]:
a = np.ones(10)
print(a)
print(a.ndim)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
1


In [56]:
a.dtype

dtype('float64')

## Acceso a los elementos de un array
Para acceder a los elementos contenidos en un array se usan índices al igual que para acceder a los elementos de una lista, pero indicando los índices de cada dimensión separados por comas.

Al igual que para listas, los índices de cada dimensión comienzan en 0.

También es posible obtener subarrays con el operador dos puntos : indicando el índice inicial y el siguiente al final para cada dimensión, de nuevo separados por comas.

In [57]:
import numpy as np

In [58]:
#Asginamos un array a una variable
arrVentas = np.array([1200,1400,3500,2300,800,600,500,325,127,428])

In [59]:
arrVentas[-1]

428

In [60]:
arrVentas[3]

2300

In [61]:
# Creamos un array de 2 dimensiones
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [62]:
#Accediendo a los datos que se encuentran dentro de un array
# Forma 1
# Primero Fila
# Segundo la columna
a2[1][2]

6

In [63]:
#Accediendo a los datos que se encuentran dentro de un array
# Esta configuracion de acceso a los datos SOLO funciona en el array.
# Forma 2
a2[1,2]

6

In [64]:
#Inicializamos un array de 3 dimensiones
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])

In [65]:
# Accediendo al valor de 15
a[2][0][2]

15

In [66]:
#Inicializamos un array de 3 dimensiones
a[2,0,2]

15

In [67]:
array1 = np.ones(10, dtype = int)
array1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [68]:
array1[3] = 10

In [69]:
array1

array([ 1,  1,  1, 10,  1,  1,  1,  1,  1,  1])

In [72]:
A = np.array([[3, 4, 5], [6, 7, 8], [9, 10, 11]])
B = np.array([[1, 2, 3], [4, 5, 5], [9, 10, 11]])
print(A)
print(B)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 1  2  3]
 [ 4  5  5]
 [ 9 10 11]]


In [73]:
A+B

array([[ 4,  6,  8],
       [10, 12, 13],
       [18, 20, 22]])

In [74]:
A-B

array([[2, 2, 2],
       [2, 2, 3],
       [0, 0, 0]])

In [75]:
A@B

array([[ 64,  76,  84],
       [106, 127, 141],
       [148, 178, 198]])

In [76]:
np.dot(A, B)

array([[ 64,  76,  84],
       [106, 127, 141],
       [148, 178, 198]])

In [77]:
A * B #aunque esto se puede hacer, no es la forma en que se multiplica una matriz

array([[  3,   8,  15],
       [ 24,  35,  40],
       [ 81, 100, 121]])

In [78]:
A.T #transpuesta, columnas se vuelven filas

array([[ 3,  6,  9],
       [ 4,  7, 10],
       [ 5,  8, 11]])

In [79]:
from numpy.linalg import det #para determinante

In [82]:
det(A)

0.0

In [81]:
det(B)

-7.999999999999995

In [85]:
from numpy.linalg import inv

In [89]:
inv(B) #inversa de A muestra error por que su determinante es cero y no se puede sacar inversa de determinante 0

array([[-0.625, -1.   ,  0.625],
       [-0.125,  2.   , -0.875],
       [ 0.625, -1.   ,  0.375]])

In [90]:
np.diag(np.ones(3)) #matriz diagonal solo tiene valores en la diagonal

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Estadística con Numpy / uso de metodos
Con la librería NUMPY se pueden realizar los siguiente cálculos estadísticos sobre una serie de datos:
* Promedio
* Mediana
* Mínimo
* Máximo
* Suma total

In [91]:
# Crear un array Numpy
arrVentas = np.array([1200,1400,3500,2300,2300,600,500,325,127,428])


In [92]:
# Calcular la media aritmetica = promedio
mean = np.mean(arrVentas)
print("Media:", mean)

Media: 1268.0


In [93]:
# Calcular la mediana
median = np.median(arrVentas)
print("Mediana:", median)

Mediana: 900.0


In [94]:
# Calcular el mínimo
min = np.min(arrVentas)
print("Mínimo:", min)

Mínimo: 127


In [95]:
# Calcular el máximo
max = np.max(arrVentas)
print("Máximo:", max)

Máximo: 3500


In [96]:
# Calcular la suma
sum = np.sum(arrVentas)
print("Suma:", sum)


Suma: 12680


## Ejercicio 1

* Crear un array Numpy con números enteros
* Crear un array Numpy con números flotantes


In [97]:
array_numero_entero = np.ones(10, dtype = int)
array_numero_entero

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [98]:
array_numero_flotante = np.ones(10)
array_numero_flotante

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Ejercicio 2

Dado el siguiente arreglo:
* array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

Se pide:
* Obtener el tercer elemento

In [99]:
array_del_1_al_10 = np.arange(1,11)
array_del_1_al_10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
array_del_1_al_10[2]

3

## Ejercicio 3
Crear un programa donde calcule el IMC para N personas, en el cual se le pregunte el peso y la estatura. Almacenar los IMC en un arreglo numpy. Otebener el promedio.
* fórmula: IMC = peso/(estatura*estatura)

In [104]:
cantidad_personas = int(input('Ingrese la cantidad de personas a calcular su IMC: '))
array_IMC = np.arange(cantidad_personas, dtype = int)
print(array_IMC)

for iterante in range(cantidad_personas): #range(3): 0,1,2
  peso = float(input('Ingrese su peso en (kg):'))
  estatura = float(input('Ingrese su altura en (m):'))
  c_imc = peso / estatura**2
  array_IMC[iterante] = c_imc

prom_imc = array_IMC.mean()
print(f'El IMC promedio de {cantidad_personas} personas es:', prom_imc)

Ingrese la cantidad de personas a calcular su IMC: 2
[0 1]
Ingrese su peso en (kg):100
Ingrese su altura en (m):1.78
Ingrese su peso en (kg):78
Ingrese su altura en (m):1.55
El IMC promedio de 2 personas es: 31.5
[31 32]


In [105]:
array_IMC

array([31, 32])

## Ejercicio 4

Para un conjunto determinado de notas (Leer de consola) implementar un algoritmo para determinar el máximo, min y prom, luego de registrar las notas en un array.

In [ ]:
cantNotas = int(input('Ingrese la cantidad de notas que desea calcular: ')) # 5
arrayNotas = np.ones(cantNotas) #np.ones(5, dtype = int)

for iterante in range(cantNotas): # range(5) = 0,1,2,3,4
  nota = float(input(f'Ingrese la nota para el alumno {iterante+1}: '))
  arrayNotas[iterante] = nota

prom = arrayNotas.mean()
max = arrayNotas.max()
min = arrayNotas.min()

print('La nota promedio es: ', prom)
print('La nota maxima es: ', max)
print('La nota minima es: ', min)

Ingrese la cantidad de notas que desea calcular: 1
Ingrese la nota para el alumno 1: 19
La nota promedio es:  19.0
La nota maxima es:  19.0
La nota minima es:  19.0


In [ ]:
arrayNotas

array([19.])

In [ ]:
contador = 1
listNotas = []

cantNotas = int(input('Ingrese la cantidad de notas a calcular: '))

while contador <= cantNotas:
  nota = int(input(f'Ingrese la nota {contador}:'))
  if nota == -1:
    break
  listNotas.append(nota)
  contador +=1

arrNota = np.array(listNotas)

notMax = np.max(arrNota)
notMin = np.min(arrNota)
notProm = np.mean(arrNota)

print(f'Nota minima: {notMin}')
print(f'Nota maxima: {notMax}')
print(f'Nota promedio: {notProm}')

Ingrese la cantidad de notas a calcular: 1
Ingrese la nota 1:19
Nota minima: 19
Nota maxima: 19
Nota promedio: 19.0


In [106]:
contador = 1
listNotas = []

cantNotas = int(input('Ingrese la cantidad de notas a calcular: '))

while contador <= cantNotas:
  nota = int(input(f'Ingrese la nota {contador}:'))
  if nota == -1:
    break
  listNotas.append(nota)
  contador +=1

#arrNota = np.array(listNotas)

notMax = np.max(listNotas)
notMin = np.min(listNotas)
notProm = np.mean(listNotas)

print(f'Nota minima: {notMin}')
print(f'Nota maxima: {notMax}')
print(f'Nota promedio: {notProm}')

Ingrese la cantidad de notas a calcular: 1
Ingrese la nota 1:10
Nota minima: 10
Nota maxima: 10
Nota promedio: 10.0


## Ejercicio 5

Registrar los sueldos y turnos (1,2,3) de un numero determinado de empleados e indique el sueldo promedio por cada turno.